apiVersion: v1
kind: Service
metadata:
  name: squeezebox
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: http2
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: udp
      port: 3483
      protocol: UDP
      targetPort: 3483
  selector:
    app: lms