apiVersion: v1
kind: Service
metadata:
  name: lms
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
    - port: 9090
      protocol: TCP
      targetPort: 9090
    - port: 3483
      protocol: UDP
      targetPort: 3483
  selector:
    app: lms