apiVersion: v1
kind: Service
metadata:
  name: lms-service
  namespace: lms
  #externalTrafficPolicy: Local
  labels:
    app: lms
spec:
  type: LoadBalancer
  selector:
    app: lms
  ports:
  - name: "web"
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: "admin"
    protocol: TCP
    port: 9090
  - name: "castbridge"
    protocol: TCP
    port: 49152
#  configIP: None
  loadBalancerIP: 192.168.1.173
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lms-ingress
  namespace: lms
  labels:
    app: lms
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: lms.local.k3s
    http:
      paths: 
      - pathType: Prefix 
        path: "/"  
        backend:
          service:
            name: lms-service
            port:
              number: 9000
