apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: lms
  template:
    metadata:
      labels:
        app: lms
    spec:
      containers:
      - image: lmscommunity/logitechmediaserver
        name: lms
        ports:
        - port: 9000
          protocoll: TCP
          targetPort: 9000
        - port: 9090
          protocoll: TCP
          targetPort: 9090
        - port: 3483
          protocoll: UDP
          targetPort: 3483
        
